#' @title Set up data and dependence structures for clustering and testing
#' @family Utilities
#' @description
#' Prepares the data matrix \code{X} and the dependence structures \code{U} and \code{Sigma} for clustering and testing. If \code{Sigma} is not provided, it is estimated using an i.i.d. sample \code{Y} of the same variables,
#' with an associated dependence structure \code{UY}. Sample splitting can be used to generate \code{Y} from \code{X} when observations are independent.
#' Checks are performed to ensure the compatibility of the dimensions of the data and dependence structures, and to verify the positive-definiteness of \code{U} and \code{Sigma}.
#' @param X Data matrix of size \eqn{n \times p} containing the observations and variables to be clustered and tested.
#' @param U Optional \eqn{n \times n} positive-definite matrix representing the dependence structure among observations in \code{X}. If not provided, observations are considered independent with unit variance.
#' @param Sigma Optional \eqn{p \times p} positive-definite matrix representing the dependence structure among variables in \code{X}. If not provided, it is estimated using \code{Y} and \code{UY}.
#' @param Y Optional \eqn{n_Y \times p} data matrix containing an i.i.d. sample of the same variables as in \code{X}, used to estimate \code{Sigma} when it is not provided. If not provided and \code{sample_split = TRUE}, \code{Y} is generated by sample splitting from \code{X}. If provided by the user, it must satisfy \eqn{n_Y > p}, i.e. \code{nrow(Y) > ncol(Y)}.
#' @param UY Optional \eqn{n_Y \times n_Y} positive-definite matrix representing the dependence structure among observations in \code{Y}. If not provided, observations in \code{Y} are considered independent with unit variance.
#' @param precUY Optional \eqn{n_Y \times n_Y} positive-definite matrix representing the inverse of \code{UY}. If \code{UY} is provided but \code{precUY} is not, \code{precUY} is computed as the inverse of \code{UY}. If neither \code{UY} nor \code{precUY} is provided, observations in \code{Y} are considered independent with unit variance.
#' @param sample_split Logical indicating whether to generate \code{Y} by sample splitting from \code{X} when \code{Sigma} is not provided. If \code{TRUE}, \code{Y} is generated by randomly splitting the observations in \code{X} into two disjoint sets, one for clustering and testing, and the other for estimating \code{Sigma}. If \code{FALSE}, an i.i.d. sample \code{Y} must be provided to estimate \code{Sigma}.
#' @param nY Optional integer specifying the number of observations in \code{Y} when \code{sample_split = TRUE}. If not provided, it defaults to half of the sample size of \code{X}. Must be strictly greater than \code{ncol(X)}.
#' @param verbose Logical. Whether to print informational messages about the setup steps (e.g., default choices for \code{U} or \code{Sigma}). Warnings are always shown regardless of this argument. Default is \code{TRUE}.
#'
#' @return A list containing the following elements:
#' \item{X}{Data matrix of size \eqn{n \times p} containing the observations and variables to be clustered and tested. If \code{sample_split = TRUE}, \code{X} contains only the observations used for clustering and testing after sample splitting.}
#' \item{U}{\eqn{n \times n} positive-definite matrix representing the dependence structure among observations in \code{X}. If not provided, it is set to the identity matrix.}
#' \item{Sigma}{\eqn{p \times p} positive-definite matrix representing the dependence structure among variables in \code{X}. If not provided, it is estimated using \code{Y} and \code{UY}.}
#' 
#' @examples
#' # Example with independent observations and known Sigma
#' X <- matrix(rnorm(100 * 5), nrow = 100, ncol = 5)
#' Sigma <- diag(5)
#' setup_result <- setup.model(X = X, Sigma = Sigma)
#' print(setup_result)
#' # Example with dependent observations and unknown Sigma, using sample splitting
#' X <- matrix(rnorm(100 * 5), nrow = 100, ncol = 5)
#' U <- matrix(0.3, nrow = 100, ncol = 100)
#' diag(U) <- 1
#' setup_result <- setup.model(X = X, U = U, sample_split = TRUE)
#' print(setup_result)
#' @export

setup.model <- function(X, U = NULL, Sigma = NULL, Y = NULL, UY = NULL, precUY = NULL, sample_split = FALSE, nY = NULL, verbose = TRUE){

  # ----------- Checks on U -----------

  if(is.null(U)){

    U <- Matrix::Diagonal(dim(X)[1]) # Independent observations by default
    if(verbose){cat('U is not provided: observations are considered independent with unit variance.\n')}
  
  }else{ 
    
    if(!matrixNormal::is.positive.definite(U)){ # Check for positive-definiteness of U
      
      stop('U must be positive-definite.')}else{ 
      
      if(!is.CS(U)){warning('U is not Compound Symmetry: selective type I error control might be lost if the deviation from the CS structure is large.\n')}
      U <- Matrix::Matrix(U) # Memory efficiency
      
    }}
  
  # ----------- Checks on Sigma -----------

  if(is.null(Sigma)){

    # ----------- Generate i.i.d. sample Y if not provided -----------
    
    if(is.null(Y) & !sample_split){  # Need to provide i.i.d. copy of Y if Sigma is NULL
    
      stop('Sigma is not provided. An i.i.d. sample Y must be provided to allow its over-estimation. Consider sample splitting if observations are independent, setting sample_split = TRUE.')  
      
    }else{
      if(is.null(Y) & sample_split){ # Y is not provided and will be generated by sample splitting

        nY <- ifelse(is.null(nY), floor(dim(X)[1]/2), nY) # Number of observations in Y, default to half of the sample size

        if(nY <= dim(X)[2]){ # nY must exceed the number of variables for Sigma to be estimable

          stop('nY must be strictly greater than ncol(X) to allow estimation of Sigma.')}

        ind_Y <- sample(1:dim(X)[1], size = nY, replace = FALSE) # Individual indices for Y
        ind_X <- setdiff(1:dim(X)[1], ind_Y) # Individual indices for X
        Y <- X[ind_Y, ] # Y is used to estimate Sigma
        X <- X[ind_X, ] # X is used to cluster and test
        UY <- U[ind_Y, ind_Y] # Subset U to the observations in Y
        U <- U[ind_X, ind_X] # Subset U to the observations in X
        precUY <- Matrix::solve(UY) # Inverse of U for Y

      }else{
        if(!is.null(Y) & sample_split){ # Y is provided but sample splitting is requested

          warning('Y has been provided and will be used to estimate Sigma. The sample_split argument will be ignored.')

        }

        # ----------- Check that user-provided Y has strictly more rows than columns -----------
        if (is.null(dim(Y)) || nrow(Y) <= ncol(Y)) {
          stop('Y must have strictly more rows than columns (nrow(Y) > ncol(Y)) to allow estimation of Sigma.')
        }
      }}

    # ----------- Check that Y and X have compatible dimensions ----------- 
    
    if(dim(Y)[2] != dim(X)[2]){
      
      stop('Y and X must have the same number of variables')} # X and Y must have the same number of features
    
    # ----------- Get U^{-1} associated to Y -----------

    if(verbose){cat('Sigma not provided: plugging an over-estimate.\n')}
    
    if(is.null(UY) & is.null(precUY)){
      
      precUY <- Matrix::Diagonal(dim(Y)[1])} # If the matrix U for Y and its inverse are not provided, independent observations by default
    
    if(is.null(precUY) & !is.null(UY)){ # U for Y is provided but not its inverse
      
      UY <- Matrix::Matrix(UY) 
      precUY <- Matrix::solve(UY)}
    
    if(!is.null(precUY)){
      
      precUY <- Matrix::Matrix(precUY)} # Provide the inverse of U for Y
    
    # ----------- Estimate Sigma using Y and precUY -----------

    if (is.data.frame(Y)) {
      if(verbose){cat("Y was provided or sampled as a data.frame and has been coerced to a Matrix.\n")}
      Y <- as.matrix(Y)
    }
    Y <- Matrix::Matrix(Y) # Memory efficiency
    Ybar <- Matrix::colMeans(Y)
    Sigma <- Matrix::crossprod(Matrix::t(1/(nrow(Y) - 1)*((Matrix::t(Y) - Ybar))),  Matrix::tcrossprod(precUY, Matrix::t(Y) - Ybar)) # Sigma estimate
    
  }else{
    
    # ----------- Known Sigma provided by the user -----------
    
    if(!matrixNormal::is.positive.definite(Sigma)){ # Check for positive-definiteness of Sigma
      
      stop('Sigma must be positive-definite.')}else{
        
        Sigma <- Matrix::Matrix(Sigma) # Memory efficiency
    }
  }

  # ----------- Checks on X -----------

  if (is.data.frame(X)) {
    if(verbose){cat("X was provided as a data.frame and has been coerced to a Matrix.\n")}
    X <- as.matrix(X)
  }
  X <- Matrix::Matrix(X)

  # ----------- Checks on compatible matrices dimensions -----------

  if(dim(X)[1] != dim(U)[1] | dim(X)[2] != dim(Sigma)[2] | dim(U)[1] != dim(U)[2] | dim(Sigma)[1] != dim(Sigma)[2]){
    
    stop('X, U and Sigma must have compatible dimensions: X is ', dim(X)[1], ' by ', dim(X)[2], ', U is ', dim(U)[1], ' by ', dim(U)[2], ' and Sigma is ', dim(Sigma)[1], ' by ', dim(Sigma)[2], '.')}


  # ----------- Return data and dependence structures -----------

  return(list(X = X, U = U, Sigma = Sigma))

}


#' @title Validate k-means clustering setting
#' @family Utilities
#' @description
#' Validates a precomputed \code{km_at_cl} object (the output of
#' \code{KmeansInference::kmeans_inference()}) against the data matrix
#' \code{X}, the requested number of clusters \code{NC} and the pair of
#' \code{clusters} to compare. Also discards \code{km_at_cl} when sample
#' splitting is requested (since \code{X} changes after splitting), checks
#' that \code{clusters} is a valid specification, and reconciles
#' \code{sample_split} with \code{return_X_clus}.
#'
#' @param km_at_cl An optional precomputed output of
#'   \code{KmeansInference::kmeans_inference()}, or \code{NULL}.
#' @param X A numeric \eqn{n \times p} data matrix.
#' @param NC Integer scalar giving the number of clusters.
#' @param clusters Integer vector of length 2 specifying the pair of clusters
#'   to compare. Entries must belong to \code{1:NC}.
#' @param sample_split Logical. Whether sample splitting is used to estimate
#'   \code{Sigma}.
#' @param return_X_clus Logical. Whether the data matrix used for clustering
#'   should be returned.
#'
#' @return A named list with:
#' \item{km_at_cl}{The validated \code{km_at_cl}, or \code{NULL} if it was
#'   not provided or was discarded because \code{sample_split = TRUE}.}
#' \item{return_X_clus}{The (possibly adjusted) \code{return_X_clus} flag.}
#'
#' @export

validate_km_setting <- function(km_at_cl, X, NC, clusters, sample_split, return_X_clus){

  # ----------- Validate precomputed km_at_cl if provided -----------
  
  if (!is.null(km_at_cl)) {
    if (!is.list(km_at_cl) || !all(c("final_cluster", "final_interval", "test_stat") %in% names(km_at_cl))) {
      stop("'km_at_cl' must be the output of 'KmeansInference::kmeans_inference()'.")
    }
    if (length(km_at_cl$final_cluster) != nrow(X)) {
      stop(paste0(
        "'km_at_cl' contains ", length(km_at_cl$final_cluster), " cluster labels but X has ", nrow(X),
        " rows. 'km_at_cl' must be computed on the same data matrix X."
      ))
    }
    km_unique <- sort(unique(as.vector(km_at_cl$final_cluster)))
    if (length(km_unique) != NC) {
      stop(paste0(
        "'km_at_cl' contains ", length(km_unique), " distinct cluster(s) but NC = ", NC, "."
      ))
    }
    if (!all(clusters %in% km_unique)) {
      stop(paste0(
        "The cluster labels in 'clusters' (", paste(clusters, collapse = ", "),
        ") are not all present in 'km_at_cl$final_cluster'."
      ))
    }
  }

  # ----------- Discard precomputed km_at_cl when sample splitting, since X changes after the split -----------
  
  if (!is.null(km_at_cl) && sample_split) {
    warning("'km_at_cl' is ignored when sample_split = TRUE because X is modified after splitting. The clustering will be recomputed on the subsample.")
    km_at_cl <- NULL
  }

  # ----------- Check for correct clustering specification -----------
  
  if(!all(clusters %in% c(1:NC)) | length(clusters) != 2){stop('clusters must be a vector of two integers between 1 and NC.')}

  # ----------- Check consistency between sample_split and return_X_clus -----------

  if(!sample_split & return_X_clus){
    warning('return_X_clus is set to FALSE because it is the same as the one passed as input.')
    return_X_clus <- FALSE
  }
  if(sample_split & !return_X_clus){
    warning('The sample used for clustering is a subsample of the one introduced as input (as sample_split is TRUE). Consider setting return_X_clus to TRUE for further analysis of the retrieved clusters.')
  }

  return(list(km_at_cl = km_at_cl, return_X_clus = return_X_clus))
}

#' @title Validate hierarchical clustering setting
#' @family Utilities
#' @description
#' Validates a precomputed hierarchical clustering object \code{hcl} and/or
#' distance object \code{dismat} against the data matrix \code{X}, infers or
#' validates the linkage criterion, and checks that \code{clusters} is a
#' valid specification. Also discards precomputed \code{hcl} and \code{dismat}
#' when sample splitting is requested (since \code{X} changes after
#' splitting), and reconciles \code{sample_split} with \code{return_X_clus}.
#'
#' @param hcl An optional precomputed hierarchical clustering object of class
#'   \code{"hclust"}, as returned by \code{fastcluster::hclust()} or
#'   \code{stats::hclust()}, or \code{NULL}.
#' @param dismat An optional precomputed squared Euclidean distance object of
#'   class \code{"dist"}, as returned by
#'   \code{stats::dist(X, method = "euclidean")^2}, or \code{NULL}.
#' @param X An \eqn{n \times p} data matrix.
#' @param NC Integer. Number of clusters in the partition obtained by cutting
#'   the hierarchical clustering tree.
#' @param clusters Integer vector of length 2 containing the labels of the
#'   two clusters to compare. Entries must belong to \code{1:NC}.
#' @param linkage Character string specifying the linkage criterion used in
#'   hierarchical clustering. Ignored (and overridden) when \code{hcl} is
#'   provided.
#' @param linkage_missing Logical. Whether \code{linkage} was left at its
#'   default (i.e., \code{missing(linkage)} in the calling function), used to
#'   decide whether to warn about a mismatch with \code{hcl$method}.
#' @param sample_split Logical. Whether sample splitting is used to estimate
#'   \code{Sigma}.
#' @param return_X_clus Logical. Whether the data matrix used for clustering
#'   should be returned.
#'
#' @return A named list with:
#' \item{hcl}{The validated \code{hcl}, or \code{NULL} if it was not provided
#'   or was discarded because \code{sample_split = TRUE}.}
#' \item{dismat}{The validated \code{dismat}, or \code{NULL} if it was not
#'   provided or was discarded because \code{sample_split = TRUE}.}
#' \item{linkage}{The validated (or \code{hcl}-inferred) linkage criterion.}
#' \item{return_X_clus}{The (possibly adjusted) \code{return_X_clus} flag.}
#'
#' @export

validate_hc_setting <- function(hcl, dismat, X, NC, clusters, linkage, linkage_missing, sample_split, return_X_clus){

  # ----------- Discard precomputed hcl and dismat when sample splitting, since X changes after the split -----------
  
  if (!is.null(hcl) && sample_split) {
    warning("'hcl' is ignored when sample_split = TRUE because X is modified after splitting. The clustering will be recomputed on the subsample.")
    hcl <- NULL
  }
  if (!is.null(dismat) && sample_split) {
    warning("'dismat' is ignored when sample_split = TRUE because X is modified after splitting. The distance matrix will be recomputed on the subsample.")
    dismat <- NULL
  }

  # ----------- Validate or infer linkage -----------
  
  if(is.null(hcl)){
    if(!linkage %in% c("single", "average", "centroid", "ward.D", "median", "mcquitty", "complete")){
      stop('linkage must be one in "single", "average", "centroid", "ward.D", "median", "mcquitty", "complete".')}
  }else{
    if (!inherits(hcl, "hclust")) {
      stop("'hcl' must be an object of class 'hclust' as returned by fastcluster::hclust() or stats::hclust().")}
    if (length(hcl$order) != nrow(X)) {
      stop(paste0(
        "'hcl' was built on ", length(hcl$order), " observations but X has ", nrow(X),
        " rows. 'hcl' must be computed on the same data matrix X."
      ))
    }
    inferred_linkage <- hcl$method
    if(!inferred_linkage %in% c("single", "average", "centroid", "ward.D", "median", "mcquitty", "complete")){
      stop(paste0('The linkage method stored in the provided hcl object ("', inferred_linkage, '") is not supported. Must be one of "single", "average", "centroid", "ward.D", "median", "mcquitty", "complete".'))}
    if(!linkage_missing && linkage != inferred_linkage){
      warning(paste0(
        'The linkage argument ("', linkage, '") does not match the method stored in the provided hcl object ("',
        inferred_linkage, '"). The linkage inferred from hcl will be used.'
      ))
    }
    linkage <- inferred_linkage
  }

  # ----------- Validate dismat class and size -----------

  if (!is.null(dismat)) {
    if (!inherits(dismat, "dist")) {
      stop("'dismat' must be an object of class 'dist' as returned by stats::dist(X, method = 'euclidean')^2.")
    }
    if (attr(dismat, "Size") != nrow(X)) {
      stop(paste0(
        "'dismat' was built on ", attr(dismat, "Size"), " observations but X has ", nrow(X),
        " rows. 'dismat' must be computed on the same data matrix X."
      ))
    }
  }

  # ----------- Warn about incomplete precomputation: dismat without hcl, or hcl without dismat -----------
  
  if (!is.null(dismat) && is.null(hcl)) {
    warning("'dismat' is provided but 'hcl' is not. The dendrogram will be computed from the provided 'dismat'. Pass 'hcl' as well to avoid recomputing it when testing multiple cluster pairs.")
  }
  if (!is.null(hcl) && is.null(dismat) && linkage != "complete") {
    warning("'hcl' is provided but 'dismat' is not. The distance matrix will be recomputed internally. Pass 'dismat' as well to avoid recomputing it when testing multiple cluster pairs.")
  }

  # ----------- Check for correct clustering specification -----------
  
  if(!all(clusters %in% c(1:NC)) | length(clusters) != 2){stop('clusters must be a vector of two integers between 1 and NC.')}

  # ----------- Check consistency between sample_split and return_X_clus -----------
  
  if(!sample_split & return_X_clus){
    warning('return_X_clus is set to FALSE because it is the same as the one passed as input.')
    return_X_clus <- FALSE
  }
  if(sample_split & !return_X_clus){
    warning('The sample used for clustering is a subsample of the one introduced as input (as sample_split is TRUE). Consider setting return_X_clus to TRUE for further analysis of the retrieved clusters.')
  }

  return(list(hcl = hcl, dismat = dismat, linkage = linkage, return_X_clus = return_X_clus))
}

#' @title Check for compound symmetry
#' @family Utilities
#' @description
#' Determines whether a square matrix exhibits compound symmetry (CS), i.e.,
#' whether all diagonal entries are equal and all off-diagonal entries are
#' equal.
#'
#' @param U A numeric square matrix.
#'
#' @return Logical. \code{TRUE} if \code{U} has compound symmetry structure,
#'   and \code{FALSE} otherwise.
#'
#' @examples
#' # Compound symmetry matrix
#' U1 <- matrix(0.3, nrow = 4, ncol = 4)
#' diag(U1) <- 1
#' is.CS(U1)
#'
#' # Toeplitz matrix, not CS
#' U2 <- toeplitz(c(1, 0.5, 0.2, 0.1))
#' is.CS(U2)
#'
#' @export

is.CS <- function(U){
  
  CS <- TRUE
  if(!matrixNormal::is.square.matrix(U)){CS <- FALSE}
  if(length(unique(U[col(U) == row(U)])) != 1){CS <- FALSE}
  if(length(unique(U[col(U) != row(U)])) != 1){CS <- FALSE}
  return(CS)  
  
}

#' @title Check for equivalent partitions
#' @family Utilities
#' @description
#' Assesses whether two selected clusters from an initial partition remain invariant under a second partition, up to relabeling. Invariance means that:
#' (i) all observations from each selected cluster remain grouped together, and (ii) no additional observations are assigned to these clusters.
#'
#' @param cl Integer vector of length \eqn{n} giving the initial cluster
#'   assignment.
#' @param cl_phi Integer vector of length \eqn{n} giving the cluster assignment
#'   after perturbation.
#' @param clusters Integer vector of length 2 specifying the labels of the
#'   clusters in \code{cl} to be tracked.
#'
#' @return Logical. \code{TRUE} if both clusters remain invariant in
#'   \code{cl_phi} (up to label permutation), and \code{FALSE} otherwise.
#' 
#' @examples
#' # Original partition
#' cl <- c(1, 1, 2, 2, 3, 3)
#'
#' # Same selected clusters up to relabeling
#' cl_phi <- c(4, 4, 5, 5, 6, 6)
#' preserve.cl(cl, cl_phi, clusters = c(1, 2))
#'
#' # Cluster 1 is no longer preserved
#' cl_phi2 <- c(4, 5, 5, 5, 6, 6)
#' preserve.cl(cl, cl_phi2, clusters = c(1, 2))
#' 
#' @export

preserve.cl <- function(cl, cl_phi, clusters) {
  
  new_cl1 <- unique(cl_phi[which(cl == clusters[1])])
  new_cl2 <- unique(cl_phi[which(cl == clusters[2])])
  
  in_k1 <- length(new_cl1) == 1 # Individuals in the first clusters stay all in the same cluster
  in_k2 <- length(new_cl2) == 1 # Individuals in the second clusters stay all in the same cluster
  distinct_k1_k2 <- length(intersect(new_cl1, new_cl2)) == 0 # The two selected clusters must map to different labels (not merged)
  
  out_k1_k2 <- all(! cl_phi[-which(cl %in% clusters)] %in% c(new_cl1, new_cl2)) # New individuals are not assigned to the new clusters after perturbation
  
  in_k1 & in_k2 & distinct_k1_k2 & out_k1_k2
}

#' @title Adjusted Rand Index
#' @family Utilities
#' @description
#' Computes the Adjusted Rand Index (ARI) between two cluster assignment
#' vectors. The ARI measures the similarity between two partitions, corrected
#' for chance. It equals 1 for identical partitions and has an expected value
#' of 0 for independent (random) partitions.
#'
#' @param cl1 Integer (or factor) vector of length \eqn{n} giving the first
#'   cluster assignment.
#' @param cl2 Integer (or factor) vector of length \eqn{n} giving the second
#'   cluster assignment.
#'
#' @return A numeric scalar in \eqn{(-1, 1]} giving the Adjusted Rand Index.
#'
#' @examples
#' # Perfect agreement
#' cl1 <- c(1, 1, 2, 2, 3, 3)
#' cl2 <- c(2, 2, 1, 1, 3, 3)  # same partition, different labels
#' ARI(cl1, cl2)  # should be 1
#'
#' # Random agreement
#' set.seed(1)
#' cl1 <- sample(1:3, 100, replace = TRUE)
#' cl2 <- sample(1:3, 100, replace = TRUE)
#' ARI(cl1, cl2)  # close to 0
#'
#' @export

ARI <- function(cl1, cl2) {

  if (length(cl1) != length(cl2)) {
    stop("cl1 and cl2 must have the same length.")
  }

  if (anyNA(cl1) || anyNA(cl2)) {
    stop("cl1 and cl2 must not contain NA values.")
  }

  # Contingency table of pair counts
  tab <- table(cl1, cl2)
  n   <- length(cl1)
  if (n < 2) return(1)

  # Choose-2 helper
  c2 <- function(x) x * (x - 1) / 2

  sum_comb_cells <- sum(c2(tab)) # sum_ij C(n_ij, 2)
  sum_comb_rows <- sum(c2(rowSums(tab))) # sum_i  C(a_i,  2)
  sum_comb_cols <- sum(c2(colSums(tab))) # sum_j  C(b_j,  2)
  total_comb <- c2(n) # C(n, 2)

  expected <- sum_comb_rows * sum_comb_cols / total_comb
  numerator   <- sum_comb_cells - expected
  denominator <- 0.5 * (sum_comb_rows + sum_comb_cols) - expected

  if (denominator == 0) return(1)  # identical or trivially degenerate partitions
  numerator / denominator
}

