#' @title Set up data and dependence structures for clustering and testing
#' @family Utilities
#' @description
#' Prepares the data matrix \code{X} and the dependence structures \code{U} and \code{Sigma} for clustering and testing. If \code{Sigma} is not provided, it is estimated using an i.i.d. sample \code{Y} of the same variables,
#' with an associated dependence structure \code{UY}. Sample splitting can be used to generate \code{Y} from \code{X} when observations are independent.
#' Checks are performed to ensure the compatibility of the dimensions of the data and dependence structures, and to verify the positive-definiteness of \code{U} and \code{Sigma}.
#' @param X Data matrix of size \eqn{n \times p} containing the observations and variables to be clustered and tested.
#' @param U Optional \eqn{n \times n} positive-definite matrix representing the dependence structure among observations in \code{X}. If not provided, observations are considered independent with unit variance.
#' @param Sigma Optional \eqn{p \times p} positive-definite matrix representing the dependence structure among variables in \code{X}. If not provided, it is estimated using \code{Y} and \code{UY}.
#' @param Y Optional \eqn{n_Y \times p} data matrix containing an i.i.d. sample of the same variables as in \code{X}, used to estimate \code{Sigma} when it is not provided. If not provided and \code{sample_split = TRUE}, \code{Y} is generated by sample splitting from \code{X}.
#' @param UY Optional \eqn{n_Y \times n_Y} positive-definite matrix representing the dependence structure among observations in \code{Y}. If not provided, observations in \code{Y} are considered independent with unit variance.
#' @param precUY Optional \eqn{n_Y \times n_Y} positive-definite matrix representing the inverse of \code{UY}. If \code{UY} is provided but \code{precUY} is not, \code{precUY} is computed as the inverse of \code{UY}. If neither \code{UY} nor \code{precUY} is provided, observations in \code{Y} are considered independent with unit variance.
#' @param sample_split Logical indicating whether to generate \code{Y} by sample splitting from \code{X} when \code{Sigma} is not provided. If \code{TRUE}, \code{Y} is generated by randomly splitting the observations in \code{X} into two disjoint sets, one for clustering and testing, and the other for estimating \code{Sigma}. If \code{FALSE}, an i.i.d. sample \code{Y} must be provided to estimate \code{Sigma}.
#' @param nY Optional integer specifying the number of observations in \code{Y} when \code{sample_split = TRUE}. If not provided, it defaults to half of the sample size of \code{X}.
#' 
#' @return A list containing the following elements:
#' \item{X}{Data matrix of size \eqn{n \times p} containing the observations and variables to be clustered and tested. If \code{sample_split = TRUE}, \code{X} contains only the observations used for clustering and testing after sample splitting.}
#' \item{U}{\eqn{n \times n} positive-definite matrix representing the dependence structure among observations in \code{X}. If not provided, it is set to the identity matrix.}
#' \item{Sigma}{\eqn{p \times p} positive-definite matrix representing the dependence structure among variables in \code{X}. If not provided, it is estimated using \code{Y} and \code{UY}.}
#' 
#' @examples
#' # Example with independent observations and known Sigma
#' X <- matrix(rnorm(100 * 5), nrow = 10, ncol = 5)
#' Sigma <- diag(5)
#' setup_result <- setup.model(X = X, Sigma = Sigma)
#' print(setup_result)
#' # Example with dependent observations and unknown Sigma, using sample splitting
#' X <- matrix(rnorm(100 * 5), nrow = 10, ncol = 5)
#' U <- matrix(0.3, nrow = 10, ncol = 10)
#' diag(U) <- 1
#' setup_result <- setup.model(X = X, U = U, sample_split = TRUE)
#' print(setup_result)
#' @export

setup.model <- function(X, U = NULL, Sigma = NULL, Y = NULL, UY = NULL, precUY = NULL, sample_split = FALSE, nY = NULL){

  # ----------- Checks on U -----------

  if(is.null(U)){
    
    U <- Matrix::Diagonal(dim(X)[1]) # Independent observations by default
    cat('U is not provided: observations are considered independent with unit variance.\n')  
  
  }else{ 
    
    if(!matrixNormal::is.positive.definite(U)){ # Check for positive-definiteness of U
      
      stop('U must be positive-definite.')}else{ 
      
      if(!is.CS(U)){warning('U is not Compound Symmetry: selective type I error control might be lost if the deviation from the CS structure is large.\n')}
      U <- Matrix::Matrix(U) # Memory efficiency
      
    }}
  
  # ----------- Checks on Sigma -----------

  if(is.null(Sigma)){

    # ----------- Generate i.i.d. sample Y if not provided -----------
    
    if(is.null(Y) & !sample_split){  # Need to provide i.i.d. copy of Y if Sigma is NULL
    
      stop('Sigma is not provided. An i.i.d. sample Y must be provided to allow its over-estimation. Consider sample splitting if observations are independent, setting sample_split = TRUE.')  
      
    }else{
      if(is.null(Y) & sample_split){ # Y is not provided and will be generated by sample splitting
        
        nY <- ifelse(is.null(nY), floor(dim(X)[1]/2), nY) # Number of observations in Y, default to half of the sample size
        ind_Y <- sample(1:dim(X)[1], size = nY, replace = FALSE) # Individual indices for Y
        ind_X <- setdiff(1:dim(X)[1], ind_Y) # Individual indices for X
        Y <- X[ind_Y, ] # Y is used to estimate Sigma
        X <- X[ind_X, ] # X is used to cluster and test
        UY <- U[ind_Y, ind_Y] # Subset U to the observations in Y
        U <- U[ind_X, ind_X] # Subset U to the observations in X
        precUY <- Matrix::solve(UY) # Inverse of U for Y

      }else{
        if(!is.null(Y) & sample_split){ # Y is provided but sample splitting is requested
        
          warning('Y has been provided and will be used to estimate Sigma. The sample_split argument will be ignored.')

        }
      }}

    # ----------- Check that Y and X have compatible dimensions ----------- 
    
    if(dim(Y)[2] != dim(X)[2]){
      
      stop('Y and X must have the same number of variables')} # X and Y must have the same number of features
    
    # ----------- Get U^{-1} associated to Y -----------

    cat('Sigma not provided: plugging an over-estimate.\n')
    
    if(is.null(UY) & is.null(precUY)){
      
      precUY <- Matrix::Diagonal(dim(Y)[1])} # If the matrix U for Y and its inverse are not provided, independent observations by default
    
    if(is.null(precUY) & !is.null(UY)){ # U for Y is provided but not its inverse
      
      UY <- Matrix::Matrix(UY) 
      precUY <- Matrix::solve(UY)}
    
    if(!is.null(precUY)){
      
      precUY <- Matrix::Matrix(precUY)} # Provide the inverse of U for Y
    
    # ----------- Estimate Sigma using Y and precUY -----------

    if (is.data.frame(Y)) {
      #warning("Y was provided or sampled as a data.frame and has been coerced to a Matrix.")
      Y <- as.matrix(Y)
    }
    Y <- Matrix::Matrix(Y) # Memory efficiency
    Ybar <- Matrix::colMeans(Y)
    Sigma <- Matrix::crossprod(Matrix::t(1/(nrow(Y) - 1)*((Matrix::t(Y) - Ybar))),  Matrix::tcrossprod(precUY, Matrix::t(Y) - Ybar)) # Sigma estimate
    
  }else{
    
    # ----------- Known Sigma provided by the user -----------
    
    if(!matrixNormal::is.positive.definite(Sigma)){ # Check for positive-definiteness of Sigma
      
      stop('Sigma must be positive-definite.')}else{
        
        Sigma <- Matrix::Matrix(Sigma) # Memory efficiency
    }
  }

  # ----------- Checks on X -----------

  if (is.data.frame(X)) {
    #warning("X was provided as a data.frame and has been coerced to a Matrix.")
    X <- as.matrix(X)
  }
  X <- Matrix::Matrix(X)

  # ----------- Checks on compatible matrices dimensions -----------

  if(dim(X)[1] != dim(U)[1] | dim(X)[2] != dim(Sigma)[2] | dim(U)[1] != dim(U)[2] | dim(Sigma)[1] != dim(Sigma)[2]){
    
    stop('X, U and Sigma must have compatible dimensions: X is ', dim(X)[1], ' by ', dim(X)[2], ', U is ', dim(U)[1], ' by ', dim(U)[2], ' and Sigma is ', dim(Sigma)[1], ' by ', dim(Sigma)[2], '.')}


  # ----------- Return data and dependence structures -----------

  return(list(X = X, U = U, Sigma = Sigma))

}


#' @title Check for compound symmetry
#' @family Utilities
#' @description
#' Determines whether a square matrix exhibits compound symmetry (CS), i.e.,
#' whether all diagonal entries are equal and all off-diagonal entries are
#' equal.
#'
#' @param U A numeric square matrix.
#'
#' @return Logical. \code{TRUE} if \code{U} has compound symmetry structure,
#'   and \code{FALSE} otherwise.
#'
#' @examples
#' # Compound symmetry matrix
#' U1 <- matrix(0.3, nrow = 4, ncol = 4)
#' diag(U1) <- 1
#' is.CS(U1)
#'
#' # Toeplitz matrix, not CS
#' U2 <- toeplitz(c(1, 0.5, 0.2, 0.1))
#' is.CS(U2)
#'
#' @export

is.CS <- function(U){
  
  CS <- TRUE
  if(!matrixNormal::is.square.matrix(U)){CS <- FALSE}
  if(length(unique(U[col(U) == row(U)])) != 1){CS <- FALSE}
  if(length(unique(U[col(U) != row(U)])) != 1){CS <- FALSE}
  return(CS)  
  
}

#' @title Check for equivalent partitions
#' @family Utilities
#' @description
#' Assesses whether two selected clusters from an initial partition remain invariant under a second partition, up to relabeling. Invariance means that:
#' (i) all observations from each selected cluster remain grouped together, and (ii) no additional observations are assigned to these clusters.
#'
#' @param cl Integer vector of length \eqn{n} giving the initial cluster
#'   assignment.
#' @param cl_phi Integer vector of length \eqn{n} giving the cluster assignment
#'   after perturbation.
#' @param clusters Integer vector of length 2 specifying the labels of the
#'   clusters in \code{cl} to be tracked.
#'
#' @return Logical. \code{TRUE} if both clusters remain invariant in
#'   \code{cl_phi} (up to label permutation), and \code{FALSE} otherwise.
#' 
#' @examples
#' # Original partition
#' cl <- c(1, 1, 2, 2, 3, 3)
#'
#' # Same selected clusters up to relabeling
#' cl_phi <- c(4, 4, 5, 5, 6, 6)
#' preserve.cl(cl, cl_phi, clusters = c(1, 2))
#'
#' # Cluster 1 is no longer preserved
#' cl_phi2 <- c(4, 5, 5, 5, 6, 6)
#' preserve.cl(cl, cl_phi2, clusters = c(1, 2))
#' 
#' @export

preserve.cl <- function(cl, cl_phi, clusters) {
  
  new_cl1 <- unique(cl_phi[which(cl == clusters[1])])
  new_cl2 <- unique(cl_phi[which(cl == clusters[2])])
  
  in_k1 <- length(new_cl1) == 1 # Individuals in the first clusters stay all in the same cluster
  in_k2 <- length(new_cl2) == 1 # Individuals in the second clusters stay all in the same cluster
  
  out_k1_k2 <- all(! cl_phi[-which(cl %in% clusters)] %in% c(new_cl1, new_cl2)) # New individuals are not assigned to the new clusters after perturbation
  
  in_k1 & in_k2 & out_k1_k2
}
